version: "3.8"
services:

  desktop:
    build:
      context: .
      dockerfile: Dockerfile
    # /dev/shm
    shm_size: '10gb'
    # use /opt as workdir
    volumes:
      - ./data:/opt/
    working_dir: /opt
    ports:
      - "6903:6901"
      - "5903:5901"
      - "2233:22"
    environment:
      - VNC_RESOLUTION=1600x900
      - VNC_PW=${ADMIN_PASSWORD:-admin}

    # resource limit
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 40g

    # for development and debugging.
    cap_add:
      - SYS_TIME
      - SYS_PTRACE

    sysctls:
      - net.ipv4.ip_forward=1
